# This file was generated by GoReleaser. DO NOT EDIT.
class Inception < Formula
  desc "scaffolding tool"
  homepage "https://github.com/sam-clough/inception"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sam-clough/inception/releases/download/v0.1.3/inception_0.1.3_Darwin_x86_64.tar.gz", :using => GitHubGitDownloadStrategy
    sha256 "95e01e8862a5641a1696066585899e3d28cee46f0988f9ff1eff2c1e3aca4da6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sam-clough/inception/releases/download/v0.1.3/inception_0.1.3_Linux_x86_64.tar.gz", :using => GitHubGitDownloadStrategy
      sha256 "6a723d64ab1df4f8679abbe13bee780b3f5309e65c0bfe75f74b96a91403a938"
    end
  end

  def install
    bin.install "inception"
  end
end
