# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Inception < Formula
  desc "scaffolding tool"
  homepage "https://github.com/sam-clough/inception"
  version "0.1.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sam-clough/inception/releases/download/v0.1.6/inception_0.1.6_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "f745ebe61de0492ffd61e03104f6c1dfb3b56766e7e1fab1223f99d2bd624eb3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sam-clough/inception/releases/download/v0.1.6/inception_0.1.6_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0f993dad3810fb65b27b8b94c5d034c63bffff8c3671efb18c3cf33fb69ecfaa"
    end
  end

  def install
    bin.install "inception"
  end
end
