# This file was generated by GoReleaser. DO NOT EDIT.
class Inception < Formula
  desc "scaffolding tool"
  homepage "https://github.com/sam-clough/inception"
  version "0.1.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sam-clough/inception/releases/download/v0.1.5/inception_0.1.5_Darwin_x86_64.tar.gz", :using => GitHubGitDownloadStrategy
    sha256 "14edbd8de649eda446f8c5416bfade676f909f2c9d0269d29af77055b5ded97c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sam-clough/inception/releases/download/v0.1.5/inception_0.1.5_Linux_x86_64.tar.gz", :using => GitHubGitDownloadStrategy
      sha256 "c63cfee8366a6acebafaf938df69230e5d18967ea462d7e7679f7f5295af6100"
    end
  end

  def install
    bin.install "inception"
  end
end
